version: '3.8'
services:
  mysql-personal-web:
    image: mysql
    container_name: mysql-personal-web
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: testing
      MYSQL_DATABASE: testing
      MYSQL_USER: testing
      MYSQL_PASSWORD: testing
    restart: always

  # phpmyadmin:
  #   image: phpmyadmin
  #   container_name: phpmyadmin
  #   ports:
  #     - '8068:80'
  #   depends_on:
  #     - mysql-personal-web
  #   restart: always
